### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by Pop0512** [TaiTair/comfyui-simswap#10]
An import failed message appears when I install the custom node. I have refreshed an restarted comfy, but it still does not work. Thanks

**Comment by Hunt3rseeker** [comment]
I'm having the same problem. I think I have everything as it should be?
![image](https://github.com/TaiTair/comfyui-simswap/assets/98604770/0803b92d-7d78-4816-950d-dd35922b7cb1)
![image](https://github.com/TaiTair/comfyui-simswap/assets/98604770/0790d4e3-2fc7-48c7-a1f2-8ace9e21d4cf)
![image](https://github.com/TaiTair/comfyui-simswap/assets/98604770/2b5cc641-b607-4d40-b9bf-9bf16c227d17)
![image](https://github.com/TaiTair/comfyui-simswap/assets/98604770/4e905e9e-9966-4405-87e2-e28446735d04)
![image](https://github.com/TaiTair/comfyui-simswap/assets/98604770/ddfe3397-e29d-40e6-8e4a-3657f6ba4526)

**Comment by TaiTair** [comment]
> I'm having the same problem. I think I have everything as it should be? ![image](https://private-user-images.githubusercontent.com/98604770/343342501-0803b92d-7d78-4816-950d-dd35922b7cb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ1MjUsIm5iZiI6MTcxOTQ0NDIyNSwicGF0aCI6Ii85ODYwNDc3MC8zNDMzNDI1MDEtMDgwM2I5MmQtN2Q3OC00ODE2LTk1MGQtZGQzNTkyMmI3Y2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDhlNGE5OTgyZmVjYmI1M2M5N2U0ZWUyNWViNjYzOWFlOWRjZjVlMWQxY2FiMzMwZmQ0NjU0MTliZjJkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gyty723PAcIf_Ru4tJKwkqjPXB-pfJCd4KVwS-hnIIA) ![image](https://private-user-images.githubusercontent.com/98604770/343342623-0790d4e3-2fc7-48c7-a1f2-8ace9e21d4cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ1MjUsIm5iZiI6MTcxOTQ0NDIyNSwicGF0aCI6Ii85ODYwNDc3MC8zNDMzNDI2MjMtMDc5MGQ0ZTMtMmZjNy00OGM3LWExZjItOGFjZTllMjFkNGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMWMzMDRiNGVjNTVmMWFkMTg3MmVkMWZjM2U1MmY0YWVmNjY4YzVmYmE1Y2U0NzI3Y2EzOGM1NjdlNGE5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSP66X6SG4Wan_ctZkfw4XfWDSt5SkGACLOxHE5MJgw) ![image](https://private-user-images.githubusercontent.com/98604770/343342666-2b5cc641-b607-4d40-b9bf-9bf16c227d17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ1MjUsIm5iZiI6MTcxOTQ0NDIyNSwicGF0aCI6Ii85ODYwNDc3MC8zNDMzNDI2NjYtMmI1Y2M2NDEtYjYwNy00ZDQwLWI5YmYtOWJmMTZjMjI3ZDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NTQ4MGYyYWRhMmQ2NmVhMzJhYTg3M2U3MDE3ZDI2YTZmMzgwNTQxOGUzMDkzZDYxNDE3ZGYzYzNhYjg3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.06elyBOAP_2y65Y5j__1zVOBOC_N2AVOT3C5ZMV3wwQ) ![image](https://private-user-images.githubusercontent.com/98604770/343342714-4e905e9e-9966-4405-87e2-e28446735d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ1MjUsIm5iZiI6MTcxOTQ0NDIyNSwicGF0aCI6Ii85ODYwNDc3MC8zNDMzNDI3MTQtNGU5MDVlOWUtOTk2Ni00NDA1LTg3ZTItZTI4NDQ2NzM1ZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZDRjMDA2N2Q5NjdjZDY2OTVlMTA2MDJlNWVhZWFmOGE4ODk1MDJiZTk5OTQ2NzU5ODBkOGE5NjQ0ZDY4NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xYm4lHdfO-faR6GlAFBeU9OxcxKWVaM_n_qYt5Kc2c8) ![image](https://private-user-images.githubusercontent.com/98604770/343342750-ddfe3397-e29d-40e6-8e4a-3657f6ba4526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NDQ1MjUsIm5iZiI6MTcxOTQ0NDIyNSwicGF0aCI6Ii85ODYwNDc3MC8zNDMzNDI3NTAtZGRmZTMzOTctZTI5ZC00MGU2LThlNGEtMzY1N2Y2YmE0NTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDIzMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNGM1MzVhMDdlOWYxZTdlMTU2ZjJkYjJhNWRmZjk1MmIyM2FhYTI5MThhNzA4ZDE2NzE0ODcyNzU3MTIwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3kprjdJOiLAEYfhoDMkOfph574ZJm28_Yxv_qCq5EyE)
> 
> My console looks like this: `23:52:30.374 [Init] === StableSwarmUI v0.6.4.1 Starting at 2024-06-26 23:52:30 === 23:52:30.412 [Init] Prepping extension: StableSwarmUI.Builtin_StabilityAPIExtension.StabilityAPIExtension... 23:52:30.420 [Init] Prepping extension: StableSwarmUI.Builtin_ScorersExtension.ScorersExtension... 23:52:30.421 [Init] Prepping extension: StableSwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension... 23:52:30.421 [Init] Prepping extension: StableSwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension... 23:52:30.422 [Init] Prepping extension: StableSwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension... 23:52:30.422 [Init] Prepping extension: StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension... 23:52:30.423 [Init] Prepping extension: StableSwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension... 23:52:30.454 [Init] Parsing command line... 23:52:30.454 [Init] Loading settings file... 23:52:30.476 [Init] Re-saving settings file... 23:52:30.493 [Init] Applying command line settings... 23:52:30.516 [Init] Prepping options... 23:52:30.544 [Init] Current git commit marked as date 2024-06-21 09:26:07 23:52:30.583 [Init] Swarm is up to date! Version 0.6.4.1 is the latest. 23:52:30.612 [Init] CPU Cores: 16 | RAM: 31.91 GiB total, 25.20 GiB available 23:52:30.612 [Init] GPU 0: NVIDIA GeForce RTX 3070 Ti | Temp 43C | Util 43% GPU, 32% Memory | VRAM 8.00 GiB total, 7.37 GiB free, 470.00 MiB used 23:52:30.650 [Init] Loading models list... 23:52:31.046 [Init] Loading backends... 23:52:31.047 [Init] Loading backends from file... 23:52:31.053 [Init] Prepping API... 23:52:31.053 [Init] Initializing backend #0 - ComfyUI Self-Starting... 23:52:31.054 [Init] Backend request handler loop ready... 23:52:31.055 [Init] Prepping webserver... 23:52:31.188 [Init] Scan for web extensions... 23:52:31.191 [Init] Readying extensions for launch... 23:52:31.191 [Init] Launching server... 23:52:31.191 [Init] Starting webserver on http://localhost:7801 23:52:31.224 [Init] Program is running. 23:52:31.708 [Info] Self-Start ComfyUI (Git Pull) exited properly. 23:52:31.714 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly. 23:52:31.715 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly. 23:52:32.292 [Info] Self-Start comfy node pull (ComfyUI-SAI_API) exited properly. 23:52:32.294 [Info] Self-Start comfy node pull (sd-dynamic-thresholding) exited properly. 23:52:32.310 [Info] Self-Start comfy node pull (comfyui_controlnet_aux) exited properly. 23:52:32.319 [Init] Self-Start ComfyUI-0 on port 7821 is loading... 23:52:40.468 [Info] Creating new admin session 'local' for ::1 23:52:41.018 [Warning] ComfyUI-0 on port 7821 stderr: Traceback (most recent call last): 23:52:41.020 [Warning] ComfyUI-0 on port 7821 stderr: File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\nodes.py", line 1906, in load_custom_node 23:52:41.021 [Warning] ComfyUI-0 on port 7821 stderr: module_spec.loader.exec_module(module) 23:52:41.021 [Warning] ComfyUI-0 on port 7821 stderr: File "<frozen importlib._bootstrap_external>", line 940, in exec_module 23:52:41.022 [Warning] ComfyUI-0 on port 7821 stderr: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed 23:52:41.023 [Warning] ComfyUI-0 on port 7821 stderr: File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-simswap\__init__.py", line 23, in <module> 23:52:41.023 [Warning] ComfyUI-0 on port 7821 stderr: from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS 23:52:41.024 [Warning] ComfyUI-0 on port 7821 stderr: File "C:\Ai_Root\SD.Swarm\dlbackend\comfy\ComfyUI\custom_nodes\comfyui-simswap\nodes.py", line 15, in <module> 23:52:41.024 [Warning] ComfyUI-0 on port 7821 stderr: from insightface.app.common import Face 23:52:41.025 [Warning] ComfyUI-0 on port 7821 stderr: ModuleNotFoundError: No module named 'insightface' 23:52:41.026 [Warning] ComfyUI-0 on port 7821 stderr: 23:52:45.794 [Init] Self-Start ComfyUI-0 on port 7821 started. `

Hi there. Looks like it has trouble loading insightface. I think that's a pip module that needs to be installed to comfyui's venv.

So first you will need to go into your comfyui folder with terminal/command prompt/powershell and then activate the venv. Then you will need to `pip install insightface`.

Let me know. Thanks.
