### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10060

### ISSUE THREAD

**Issue by jasoncow007** [TaiTair/comfyui-simswap#6]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "D:\ComfyUI-aki-v1.2\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 125, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 105, in get_model_names
    models = get_models()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 99, in get_restorers
    download(model_url, model_path, model_name)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\simswap_utils.py", line 106, in download
    request = urllib.request.urlopen(url)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

**Comment by jasoncow007** [comment]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ERROR] An error occurred while retrieving information for the 'SimswapFaceSwapOpt' node.
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "D:\ComfyUI-aki-v1.2\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 345, in INPUT_TYPES
    "face_restore_model": (get_model_names(get_restorers),),
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 105, in get_model_names
    models = get_models()
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\nodes.py", line 99, in get_restorers
    download(model_url, model_path, model_name)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\comfyui-simswap\simswap_utils.py", line 106, in download
    request = urllib.request.urlopen(url)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\ComfyUI-aki-v1.2\python\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
